### PR TITLE
Fixed install instructions

### PR DESCRIPTION
**Pull request by MrSchism**
Minor fix to install instructions.

### CODE REVIEW

**Comment by MrSchism** [comment]
Closing; I've got to re-pull.  One second....

**Comment by RyanRiffle** [comment]
Why do you have to re-pull?

**Comment by RyanRiffle** [comment]
Nevermind I see why you had to re-pull

**Comment by MrSchism** [comment]
Yeah, I had an old copy of the branch.  I'm running on a slow connection and because I forgot to pull from base before updating, I had to undo what I did.

**Pull request closed without merging**
